/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Automotive 3D (https://sketchfab.com/automotive3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-carrera-gt-2003-street-1880cd019d6f4bc2a8aec8a220bd5f0c
Title: Porsche Carrera GT 2003 Street
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model3({color}) {
  const { nodes, materials } = useGLTF("/models/porsche_gt_2003.glb");
  return (
    <group dispose={null} scale={2.5}>
      <group
        position={[0, -0.007, 0.087]}
        rotation={[3.135, 0, Math.PI]}
        scale={0.869}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
        //   material={materials.Main_Paint}
        ><meshStandardMaterial color={color}/></mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Tail_Lights}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Globes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Mirrors}
        />
      </group>
      <group position={[0, 0.06, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.Gold}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Rims}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.Tyres}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.Calipers}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.Chrome}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.Brakes}
      />
    </group>
  );
}

useGLTF.preload("/models/porsche_gt_2003.glb");
